In [2]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [15]:
A=np.array([[40,27,8],[5,53,0],[7,9,85]])
print (A)
A[[0,1]]=A[[1,0]]
print(f"modified row ia{A}")
#A([0,2])=A([2,0])

[[40 27  8]
 [ 5 53  0]
 [ 7  9 85]]
modified row ia[[ 5 53  0]
 [40 27  8]
 [ 7  9 85]]


**75. How to compute averages using a sliding window over an array?**

In [29]:
def slid_avg(a, b=3) :
    cs = np.cumsum(a, dtype=float)
    cs[b:] = cs[b:] - cs[:-b]
    return cs[b - 1:] / b

a = np.arange(20)
print(a)
slid_avg(a)
slid_avg(a, b=4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5,
       12.5, 13.5, 14.5, 15.5, 16.5, 17.5])