In [2]:
# Import the needed libraries
import numpy as np

**34. How to get all the dates corresponding to the month of July 2016**

In [3]:
print("Dates in July 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

Dates in July 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**42. Consider two random array A and B, check if they are equal**

In [11]:
A= np.array([[4,3],[5,3],[6,6]])
B= np.array([[5,3],[5,5],[6,6],[5,5]])
C= np.array([[5,3],[5,5],[6,6]])
print(B)
print(A)
A==B
A==C

[[5 3]
 [5 5]
 [6 6]
 [5 5]]
[[4 3]
 [5 3]
 [6 6]]
<ipython-input-11-811d2de86dcb>:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  A==B


array([[False,  True],
       [ True, False],
       [ True,  True]])