In [1]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [21]:
a= np.random.uniform(size=(10,10))
print(a)
h=a.min()
g=a.max()
print(f"Maximum value is{h}")
print(f"Minimum value is{g}")

[[0.03284661 0.22670605 0.4756881  0.08887698 0.34704136 0.0369017
  0.17460143 0.41353733 0.60185499 0.19640232]
 [0.82708208 0.95175171 0.9770669  0.87870212 0.77847845 0.08980411
  0.06056746 0.46528906 0.51282846 0.18407315]
 [0.16446407 0.46216261 0.08867105 0.75451867 0.1758114  0.95865302
  0.27520335 0.09694327 0.48001248 0.34532409]
 [0.51543825 0.17424203 0.14891085 0.78679406 0.47310422 0.91872419
  0.64317455 0.69023366 0.36645524 0.81250814]
 [0.89397279 0.34118742 0.71371602 0.29112684 0.7202595  0.42811244
  0.2690837  0.66712307 0.95069442 0.11522216]
 [0.94035557 0.69006474 0.73643138 0.58525438 0.84574817 0.25374085
  0.45377639 0.67973397 0.60549348 0.19462446]
 [0.4652114  0.6274736  0.09362949 0.58513635 0.3656369  0.23453867
  0.96936075 0.17812878 0.94680888 0.20530229]
 [0.8805645  0.29858819 0.84018339 0.67513678 0.82720739 0.26972302
  0.36254559 0.82161201 0.14416459 0.47882967]
 [0.2405504  0.40141426 0.06734748 0.24992642 0.57125366 0.79538973
  0.44859017 

**15. Create a 2d array with 1 on the border and 0 inside**

In [27]:
z = np.ones((4,4))
print(z)
z[1:3,1:3] = 0
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
